### ISSUE TITLE
Fix security problems

### ISSUE THREAD

**Issue by SuperAuguste** [sourcegraph/zendesk-discord-integration#10]
There are a few attack surfaces here that need to be fixed before deployment:
- [x] `/attachment/*` (Proxy, potential DOS)
  - Fix: Add JWT to query of attachment URL
- [x] `/pull` (Exposes Discord messages, breaks functionality, DOS with a rogue bot registration)
  - Fix: [verify token](https://developer.zendesk.com/api-reference/ticketing/account-configuration/channel_framework/#validate-token) - still vulnerable to replays
- [x] `/channelback` (Allows attacker to send Discord messages)
  - Fix: [verify token](https://developer.zendesk.com/api-reference/ticketing/account-configuration/channel_framework/#validate-token) - still vulnerable to replays
- [x] `/clickthrough` (Allows attacker to match Zendesk external ID and Discord thread ID) - this is not a huge deal because the external id is just the Discord thread ID
  - Fix: [verify token](https://developer.zendesk.com/api-reference/ticketing/account-configuration/channel_framework/#validate-token) - still vulnerable to replays
- [x] `/webhook` (Allows attacker to spoof ticket status) - not a huge deal but would still be nice to prevent as this could still cause breakage
  - Fix: use webhook HMAC provided by Zendesk

We also need to make sure we're not vulnerable to DOS via JS errors (we need to add try and catches everywhere).

**Comment by jdorfman** [comment]
yee-haw
